# Generated by Django 2.0.5 on 2018-05-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechdb_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action_type',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
