# Generated by Django 2.0.5 on 2018-05-26 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mechdb_core', '0002_auto_20180526_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='manufacturer',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='spare_part',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='supply_provider',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='equipment_sizename',
            name='title',
            field=models.CharField(default='Enter product name...', max_length=200),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='sizename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechdb_core.Equipment_sizename'),
        ),
    ]
