# Generated by Django 2.0.5 on 2018-05-26 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mechdb_core', '0003_auto_20180526_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='supply_provider',
        ),
        migrations.AddField(
            model_name='equipment_sizename',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mechdb_core.Manufacturer'),
        ),
        migrations.AddField(
            model_name='equipment_sizename',
            name='supply_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mechdb_core.Supply_provider'),
        ),
    ]
