# Generated by Django 2.0.5 on 2018-05-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechdb_core', '0008_auto_20180530_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='supply_provider',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='spare_part',
            name='supply_provider',
        ),
        migrations.AlterField(
            model_name='equipment_sizename',
            name='manufacturer',
            field=models.CharField(default='н/д', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment_sizename',
            name='supply_provider',
            field=models.CharField(default='н/д', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment_sizename',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='manufacturer',
            field=models.CharField(default='н/д', max_length=100),
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
        migrations.DeleteModel(
            name='Supply_provider',
        ),
    ]
