# Generated by Django 2.0.5 on 2018-06-01 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mechdb_core', '0009_auto_20180531_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
