# Generated by Django 2.0.5 on 2018-06-01 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mechdb_core', '0010_action_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='used_in_equipment',
        ),
        migrations.AddField(
            model_name='action',
            name='used_in_equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mechdb_core.Equipment'),
            preserve_default=False,
        ),
    ]
