# Generated by Django 2.0.5 on 2018-06-01 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mechdb_core', '0011_auto_20180601_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='in_container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechdb_core.Container'),
        ),
    ]
