# Generated by Django 2.0.5 on 2018-06-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechdb_core', '0012_auto_20180602_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare_part',
            name='suply_provider',
            field=models.CharField(default='н/д', max_length=100),
        ),
    ]
