# Generated by Django 2.0.5 on 2018-06-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechdb_core', '0013_spare_part_suply_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='action_type',
            name='only_repair_containers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='action_type',
            name='used_in_actions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='action_type',
            name='used_in_equipments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='action_type',
            name='used_in_movement_actions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='action_type',
            name='used_in_spare_parts',
            field=models.BooleanField(default=True),
        ),
    ]
