# Generated by Django 2.0.5 on 2018-06-03 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechdb_core', '0014_auto_20180602_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='in_container_id',
            new_name='in_container',
        ),
    ]
