# Generated by Django 2.0.5 on 2018-06-03 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mechdb_core', '0015_auto_20180603_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='in_container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mechdb_core.Container'),
        ),
    ]
