# Generated by Django 2.0.5 on 2018-06-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechdb_core', '0016_auto_20180603_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
