# Generated by Django 2.0.5 on 2018-06-03 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mechdb_core', '0018_auto_20180603_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='in_container',
        ),
        migrations.RemoveField(
            model_name='movement_action',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='movement_action',
            name='used_spare_part',
        ),
        migrations.RemoveField(
            model_name='spare_part',
            name='quantity',
        ),
        migrations.AddField(
            model_name='container',
            name='in_container_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movement_action',
            name='quantity_delta',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='movement_action',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mechdb_core.Action_type'),
        ),
        migrations.AddField(
            model_name='movement_action',
            name='used_in_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mechdb_core.Equipment'),
        ),
        migrations.AddField(
            model_name='movement_action',
            name='used_in_spare_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mechdb_core.Spare_part'),
        ),
        migrations.AlterField(
            model_name='container',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
