# Generated by Django 2.0.5 on 2018-06-03 22:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mechdb_core', '0019_auto_20180604_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement_action',
            name='new_container',
        ),
        migrations.RemoveField(
            model_name='movement_action',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='movement_action',
            name='type',
        ),
        migrations.RemoveField(
            model_name='movement_action',
            name='used_in_action',
        ),
        migrations.RemoveField(
            model_name='movement_action',
            name='used_in_equipment',
        ),
        migrations.RemoveField(
            model_name='movement_action',
            name='used_in_spare_part',
        ),
        migrations.AddField(
            model_name='action',
            name='new_container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mechdb_core.Container'),
        ),
        migrations.AddField(
            model_name='action',
            name='quantity_delta',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='used_in_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mechdb_core.Action'),
        ),
        migrations.AddField(
            model_name='action',
            name='used_in_spare_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mechdb_core.Spare_part'),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='action',
            name='used_in_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mechdb_core.Equipment'),
        ),
        migrations.DeleteModel(
            name='Movement_action',
        ),
    ]
