# Generated by Django 2.0.5 on 2018-06-03 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mechdb_core', '0020_auto_20180604_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='in_container_id',
        ),
        migrations.AddField(
            model_name='container',
            name='in_container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mechdb_core.Container'),
        ),
    ]
