# Generated by Django 2.0.5 on 2018-06-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechdb_core', '0021_auto_20180604_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='scheduled',
            field=models.NullBooleanField(default=None),
        ),
    ]
