# Generated by Django 2.0.5 on 2018-06-07 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechdb_core', '0023_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
