# Generated by Django 2.0.5 on 2018-06-07 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechdb_core', '0024_remove_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action_type',
            name='used_in_actions',
        ),
        migrations.RemoveField(
            model_name='action_type',
            name='used_in_equipments',
        ),
        migrations.RemoveField(
            model_name='action_type',
            name='used_in_movement_actions',
        ),
        migrations.RemoveField(
            model_name='action_type',
            name='used_in_spare_parts',
        ),
    ]
