# Generated by Django 2.0.5 on 2018-06-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechdb_core', '0025_auto_20180608_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('equipment,repair,TO', 'ТО'), ('equipment,repair,TR', 'ТР'), ('equipment,repair,KR', 'КР'), ('equipment,repair,KTS', 'КТС'), ('equipment,repair,DEFF', 'ремонт'), ('equipment,INFO', 'информация'), ('equipment,FAILURE', 'отказ'), ('equipment,REPAIR_EXPORT', 'вывоз в ремонт'), ('equipment,REPAIR_IMPORT', 'завоз с ремонта'), ('equipment,MOUNT', 'монтаж'), ('equipment,UNMOUNT', 'демонтаж'), ('equipment,MOVE', 'перемещение'), ('action,INFO', 'информация'), ('action,MOVE', 'перемещение'), ('child,OUTGO', 'расход')], default='equipment,INFO', max_length=25),
        ),
        migrations.DeleteModel(
            name='Action_type',
        ),
    ]
