# Generated by Django 2.0.5 on 2018-06-08 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mechdb_core', '0026_auto_20180608_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='used_in_container',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='used_in_container', to='mechdb_core.Container'),
        ),
        migrations.AlterField(
            model_name='action',
            name='new_container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_container', to='mechdb_core.Container'),
        ),
    ]
